//GET product
export const GET_PRODUCT_PROGRESS = "GET_PRODUCT_PROGRESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

//POST product
export const POST_PRODUCT_PROGRSS = "POST_PRODUCT_PROGRESS";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR";

//DELETE product
export const DELETE_PRODUCT_PROGRSS = "DELETE_PRODUCT_PROGRESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

//PUT product
export const PUT_PRODUCT_PROGRSS = "PUT_PRODUCT_PROGRESS";
export const PUT_PRODUCT_SUCCESS = "PUT_PRODUCT_SUCCESS";
export const PUT_PRODUCT_ERROR = "PUT_PRODUCT_ERROR";