export const GET_DATA_PROGRESS = "GET_DATA_PROGRESS";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_ERROR = "GET_DATA_ERROR";

export const POST_DATA_PROGRESS = "POST_DATA_PROGRESS";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_ERROR = "POST_DATA_ERROR";

export const DELETE_DATA_PROGRESS = "DELETE_DATA_PROGRESS";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_ERROR = "DELETE_DATA_ERROR";

export const UPDATE_DATA_PROGRESS = "UPDATE_DATA_PROGRESS";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const UPDATE_DATA_ERROR = "UPDATE_DATA_ERROR";